#服务端口
server:
  port: 8004

spring:
  application:
    #服务名
    name: service-vod
  profiles:
    #环境设置：dev、test、prod.
    active: dev

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
