#服务端口
server:
  port: 8004

spring:
  application:
    #服务名
    name: service-vod
  profiles:
    #环境设置：dev、test、prod.
    active: dev

  #springcloud nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

# 开启熔断机制
feign:
  hystrix:
    enabled: true

# 设置hystrix超时时间，默认1000ms
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
