#### application.yml
spring:

  application:
    name: service-msm

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.138.111.63:3306/guli?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: GuliHikariPool

  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  profiles:
    active: dev

  #springcloud nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  redis:
    host: 43.138.111.63
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0

####  application-dev.yml
server:
  port: 8006

mybatis-plus:
  # mybatis-plus日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 编译xml文件，将mapper的xml文件编译到target中，防止找不到mapper接口中的方法
  mapper-locations: classpath:com/atguigu/msmservice/mapper/xml/*.xml

  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

# 开启熔断机制
feign:
  hystrix:
    enabled: true

# 设置hystrix超时时间，默认1000ms
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

# 自定义参数
custom-parameters:
  # 短信验证码
  send-msg:
    # 是否启用短信发送验证码
    enable: false
    # 腾讯云账户密钥对Id
    secret-id: AKIDX0V3SjmbGwdM1c8whMxRTXaVHqFYikeL
    # 腾讯云账户密钥对Key
    secret-key: c5OfwFZoHZlssjZJxhIgu7Nf2SsLuMn6
    # SDK默认超时时间
    conn-timeout: 5
    # 短信应用ID
    sdk-app-id: 1400677800
    # 短信签名
    sign-name: 蛋蛋编程
    # 模板ID
    template-id: 1401840
    # 消息头
    msg-head: 【谷粒学苑】
