#### application.yml
spring:

  application:
    name: service-cms

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.138.111.63:3306/guli?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: MySQL5.7

  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  profiles:
    active: dev

####  application-dev.yml
server:
  port: 8005
mybatis-plus:
  # mybatis-plus日志
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 编译xml文件，将mapper的xml文件编译到target中，防止找不到mapper接口中的方法
  mapper-locations: classpath:com/atguigu/eduservice/mapper/xml/*.xml

