#服务端口
server:
  port: 8003

spring:
  application:
    #服务名
    name: service-cos
  profiles:
    #环境设置：dev、test、prod.
    active: dev

  #springcloud nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
