#### application.yml
spring:

  application:
    name: service-order

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.138.111.63:3306/guli?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: MySQL5.7

    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: GuliHikariPool

  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  profiles:
    active: dev

  # redis配置
  redis:
    host: 43.138.111.63
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0

  #springcloud nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

####  application-dev.yml
server:
  port: 8007

mybatis-plus:
  # mybatis-plus日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 编译xml文件，将mapper的xml文件编译到target中，防止找不到mapper接口中的方法
  mapper-locations: classpath:com/atguigu/orderservice/mapper/xml/*.xml

  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

# 开启熔断机制
feign:
  hystrix:
    enabled: true

# 设置hystrix超时时间，默认1000ms
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

# 自定义参数
custom-parameters:
  # 微信支付参数
  wx-pay:
    #关联的公众号appid
    app-id: wx74862e0dfcf69954
    #商户号
    partner: 1558950191
    #商户key
    partner-key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    #回调地址
    notify-url: http://guli.shop/api/order/weixinPay/weixinNotify
    #支付地址
    addr: 127.0.0.1
