#服务端口
server:
  port: 8002

spring:
  application:
    #服务名
    name: service-oss
  profiles:
    #环境设置：dev、test、prod.
    active: dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  #springcloud nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# 开启熔断机制
feign:
  hystrix:
    enabled: true

# 设置hystrix超时时间，默认1000ms
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

#阿里云 OSS
#不同的服务器，地址不同
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: xxxxxxxxxxxxxxxxxxxxxxxxxxx
      keysecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      bucketname: guli-edu-lk
      filepath: guli-edu/avatar/
