#### application.yml
spring:

  application:
    name: service-edu

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.138.111.63:3306/guli?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: MySQL5.7

    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: GuliHikariPool

  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  profiles:
    active: dev

# 设置日志级别
#logging:
#  level:
#    root: INFO

####  application-dev.yml
server:
  port: 8001

mybatis-plus:
  # mybatis-plus日志
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  # 编译xml文件，将mapper的xml文件编译到target中，防止找不到mapper接口中的方法
  mapper-locations: classpath:com/atguigu/eduservice/mapper/xml/*.xml

  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

